### PR TITLE
Use separate factory methods in WindowManager in order to preserve its prototype (fixes #66)

### LINKED ISSUE #66: WindowManager.prototype is polluted by multiple instances.
I'm creating this issue with the intention of submitting a PR for it soon.

When multiple instances of `WindowManager` are created, its `prototype` is polluted by these two lines in the constructor:
```
		// Binding sub-functions to this object
		this.createWindow.fromQuery = this.createWindow.fromQuery.bind(this);
		this.createWindow.fromElement = this.createWindow.fromElement.bind(this);
```
The `createWindow` method is of course assigned from the prototype to every instance, so setting properties on this method will of course set those properties for every instance as well. This means that after the first time the constructor is run, the two properties are set to bound functions. Creating a second instance will only attempt to bind already bound functions, resulting in the wrong context being used for subsequent instances of `WindowManager`.

Arguably, this library was not written with the intention of supporting multiple instances of `WindowManager` (given the way it modifies the DOM on the top-level and such); however, the pollution of the prototype is of a great enough concern that I believe this issue still warrants fixing.

### PR DESCRIPTION
**Pull request by JoshuaCWebDeveloper**
This PR fixes #66.

When multiple instances of `WindowManager` are created, its `prototype` is polluted by the constructor setting the `fromQuery()` and `fromElement()` methods as properties on the `createWindow` method in the prototype.

This results in multiple instances of `WindowManager` having the wrong context bound to their factory methods. 

Unfortunately, I was unable to come up with a way to maintain the current API and _not_ end up polluting the prototype of multiple instances in one way or another. Therefore, this PR creates new API methods: `createWindowFromElement` and `createWindowFromQuery` and deprecates the existing methods: `createWindow.fromElement` and `createWindow.fromQuery` for future removal.

### CODE REVIEW

**Comment by amatiasq** [comment]
I agree with this solution but I would also like to point that this could be fixed with just four lines in WindowManager by replacing [this two lines](https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/windowmanager.js#L48-L49):

```javascript
var createWindow = this.createWindow;
this.createWindow = createWindow.bind(this);
this.createWindow.fromQuery = createWindow.fromQuery.bind(this);
this.createWindow.fromElement = createWindow.fromElement.bind(this);
```

**Comment by rlamana** [comment]
Nice catch! and thank you for the PR. When Ventus was created I had in mind supporting multiple window managers, but never really had the time to focus on it, neither had a use case where I could benefit from it.

As for your PR, I'd rather fix it the way @amatiasq suggests, this way we keep the current syntax and avoid deprecating the old method. I'm aware it is an uncommon way of defining methods in a library, but this was sort of an experiment to define a more declarative and clean syntax (inspired by some behaviour-driven testing frameworks) and I'd like to keep it the way it was conceived back then.

WDYT?

**Comment by JoshuaCWebDeveloper** [comment]
@amatiasq Nice solution, I didn't think of that before when I was searching for a way that didn't break the existing API.

@rlamana One of should test his solution first to make sure it fixes the problem. I can do it tomorrow if you want to wait until then.

**Comment by rlamana** [comment]
@JoshuaCWebDeveloper I can't at the moment, it would be great if you can do it. Thanks a lot for your contribution!

**Comment by JoshuaCWebDeveloper** [comment]
@rlamana My apologies for my silence the past several days. I finally got around to testing @amatiasq's solution and confirmed that it worked. I've updated this PR with reverts to my previous commits and a commit with the new solution.

**Comment by rlamana** [comment]
@JoshuaCWebDeveloper thanks a lot for this fix!

**Pull request merged**
