### PR TITLE
Changed minimizing and maximazing to animated

### PR DESCRIPTION
**Pull request by brammittendorff-dd**
- Added forgotten animated for minimizing and maximazing

### CODE REVIEW

**Comment by rlamana** [comment]
@brammittendorff-dd Some styles from the last PR breaking the library. The CSS wm-window.animated selector should only contain animation rules, not all of the window styles.

**Comment by rlamana** [comment]
I'm working on a PR to fix those issues.

**Comment by rlamana** [comment]
@brammittendorff-dd, I have fixed this and other issues in https://github.com/rlamana/Ventus/commit/acfcce0eb279149c1e6bcbe689e1edd3c18d77f3

It was more complicated for some of the actions (max, min, close and open) relying on the transition-end or animation-end events.

**Comment by brammittendorff-dd** [comment]
Amazing!

**Pull request closed without merging**
